spring:
  datasource:
    url: jdbc:postgresql://localhost:45432/chat
    username: chat
    password: changeme
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
  security:
    user:
      name: admin
      password: password
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: chat
    liquibase-schema: chat
    database-change-log-table: databasechangelog
    database-change-log-lock-table: databasechangeloglock


security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
